


# quorum transaction manager keys transaction manager key: used for private transactions.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-tm-key-config
  
  labels:
    app: qubernetes
    name: quorum-node1-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"QA5Sc9n64Xdd9yz+DMGbwahq51n75+D0obDGLt4uOGQ="},"type":"unlocked"}
  tm.pub: |-
    7ribX/mH/HBhVT37cF1Ntk1fBK84jlOQ00pF7s6oijo=
---
# nodekey private to the node, used to verify identity.
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-nodekey-config
  
  labels:
    app: qubernetes
    name: quorum-node1-nodekey-config
data:
  nodekey: |
    12d89d4a5cc970b9f59b6b5ddf428c7449b5bb62ec637a6a7e59c045db256886
# Only IBFT / istanbul networks need access to the nodekey address.
---
# nodekey address public and used to generate istanbul-validator-config.toml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-nodekey-address-config
    
  labels:
    app: qubernetes
    name: quorum-node1-nodekey-address-config
data:
  nodekey: |
      0x228dB95f0f2be002fea420829e9502D8E3B76d6E
    
---
# enode Id
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-enode-config
  
  labels:
    app: qubernetes
    name: quorum-node1-enode-config
data:
  enode: |
    75796f5803e678bcd9bbf8371f6ea70c03a065233300346055a9bca5e1e4e988d8148a48326d449d54c55ea4e87bcf02d4ff474320b2b4a02879f49d93165969

---
# ethereum / geth account keys (keystore)
# @Keystore_File=Dir[@Key_Dir_Base + "/" + @Node_Key_Dir + "/UTC*"][0]
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-account-key-config
  
  labels:
    app: qubernetes
    name: quorum-node1-account-key-config
data:
  key: |-

    {"address":"f6ba36b93b7df6a7c5ad2bfc842db1b7a0460057","crypto":{"cipher":"aes-128-ctr","ciphertext":"e0348c9296693056cf9657ff29cb49720854f88aa75442564815200d89a5273a","cipherparams":{"iv":"51ff517cf0cefe05f93681533f1983a8"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"58512eb3e87de94ac8e694526227c418395bc1e9f962847cb0fb950e77c5f79a"},"mac":"b0f01d9fd900fbfeffefeb4adfb91afecdb2f38b4a18ffbe1be0e2c601bce4c3"},"id":"824b2e03-0009-4c0e-ba7e-2bb0cce8d4e7","version":3}
# end node

# quorum transaction manager keys transaction manager key: used for private transactions.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-tm-key-config
  
  labels:
    app: qubernetes
    name: quorum-node2-tm-key-config
data:
  tm.key: |-
    {"data":{"bytes":"wKDzW+p6grb3GZJc0xydDmicXNiT2pFSE5ED/tfhAVw="},"type":"unlocked"}
  tm.pub: |-
    LpZvDbO4BBr1e0mBbmY4jwzPbLBSCVmi3TpFVLMtZDo=
---
# nodekey private to the node, used to verify identity.
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-nodekey-config
  
  labels:
    app: qubernetes
    name: quorum-node2-nodekey-config
data:
  nodekey: |
    ba03f1d72d714607f268435fc785409cd54dccaed5fb04f9c9e84b55340b342e
# Only IBFT / istanbul networks need access to the nodekey address.
---
# nodekey address public and used to generate istanbul-validator-config.toml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-nodekey-address-config
    
  labels:
    app: qubernetes
    name: quorum-node2-nodekey-address-config
data:
  nodekey: |
      0x99F1E0B789a9dF9F4632DA27FbfEe2b7B63c3123
    
---
# enode Id
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-enode-config
  
  labels:
    app: qubernetes
    name: quorum-node2-enode-config
data:
  enode: |
    2dea3a3a06bad34d2e3ba308354f513758fb731c02811daf24c56068c934ff4427a130ad7a64eae7a7c448d738082cc24bc46c9f1908a700ff5d2edde1eebe7d

---
# ethereum / geth account keys (keystore)
# @Keystore_File=Dir[@Key_Dir_Base + "/" + @Node_Key_Dir + "/UTC*"][0]
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-account-key-config
  
  labels:
    app: qubernetes
    name: quorum-node2-account-key-config
data:
  key: |-

    {"address":"8124024ffa1941ba59ab7c826530dcf093305a3b","crypto":{"cipher":"aes-128-ctr","ciphertext":"5d30225ae130bb517acc879757ae2fb34b0403e4687694001fc7f9235c4a9e5f","cipherparams":{"iv":"6f036028b3a63c0e69477a5c8f868169"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"876888913209d7a593e7f6e36579f073ca39c9a7b8861d919f5f3f6a53b94b1a"},"mac":"e1c823a22a472b4e4c0d2f70c4478d86bb2b1f1c2f9a0c25f01cc6b861033530"},"id":"f64bb485-89f9-4b67-9296-0cb6408391b7","version":3}
# end node

